// <auto-generated />
namespace RateMyDebate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class password2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(password2));
        
        string IMigrationMetadata.Id
        {
            get { return "201409151039375_password2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
